display_name: "MIDI to MML"
publisher_display_name: cuikho210
identity_name: cuikho210.MIDItoMML
msix_version: 1.0.0.0
logo_path: ./icon.png
publisher: CN=686422A7-5A4A-4633-BAB3-4CB07D6870A6
store: "true"
