name: Build and release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    permissions: write-all
    defaults:
      run:
        working-directory: ./gui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install rinf
        run: cargo install rinf
      - name: Generate message code
        run: rinf message

      - name: Build for windows
        run: flutter build windows
      - name: Zip the windows release
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -Destination windows_portable_release_x86_64.zip

      - name: Create upload keystore file
        run: |
          $bytes = [Convert]::FromBase64String("${{ secrets.KEYSTORE_BASE64 }}")
          [IO.File]::WriteAllBytes("D:/keystore.jks", $bytes)
      - name: Create key.properties file
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > ./android/key.properties
          echo "keyPassword=${{ secrets.KEYSTORE_PASSWORD }}" >> ./android/key.properties
          echo "keyAlias=upload" >> ./android/key.properties
          echo "storeFile=D:/keystore.jks" >> ./android/key.properties
      - name: Build apk
        run: flutter build apk --release

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            windows_portable_release_x86_64.zip
            build/app/outputs/flutter-apk/app-release.apk
