name: Build and release
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./gui
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - name: Install rinf
        run: cargo install rinf
      - name: Generate message code
        run: rinf message

      - name: Build for windows
        run: flutter build windows
      - name: Zip the windows release
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -Destination windows_portable_release_x86_64.zip

      - name: Build apk
        run: flutter build apk --release

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Release"
          files: |
            windows_portable_release_x86_64.zip
            build/app/outputs/flutter-apk/app-release.apk
